using System.Text;
using System.Text.Json;
using QualityAgent.Core.Pipeline;

namespace QualityAgent.Core.Reports;

public static class ReportWriter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true
    };

    public static async Task WriteAsync(QualityReport report, string markdownPath, string jsonPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(markdownPath) ?? "artifacts");
        Directory.CreateDirectory(Path.GetDirectoryName(jsonPath) ?? "artifacts");

        await File.WriteAllTextAsync(markdownPath, BuildMarkdown(report), Encoding.UTF8);
        await File.WriteAllTextAsync(jsonPath, JsonSerializer.Serialize(report, JsonOptions), Encoding.UTF8);
    }

    private static string BuildMarkdown(QualityReport r)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# QualityAgent Report");
        sb.AppendLine();
        sb.AppendLine($"- Generated (UTC): {r.GeneratedAtUtc:O}");
        if (!string.IsNullOrWhiteSpace(r.Branch)) sb.AppendLine($"- Branch: `{r.Branch}`");
        if (r.PullRequest.HasValue) sb.AppendLine($"- Pull Request: `{r.PullRequest.Value}`");
        sb.AppendLine($"- Outcome: **{r.Outcome}**");
        sb.AppendLine();

        if (r.AutoFix is not null)
        {
            sb.AppendLine("## AutoFix Summary");
            sb.AppendLine();
            sb.AppendLine($"- Dotnet format applied: {(r.AutoFix.DotnetFormatApplied ? "YES" : "NO")}");
            sb.AppendLine($"- AI fixes applied: {r.AutoFix.AiFixesApplied}");
            if (r.AutoFix.FilesTouched.Count > 0)
                sb.AppendLine($"- Files touched: {r.AutoFix.FilesTouched.Count}");
            sb.AppendLine();
        }

        if (r.Steps.Count > 0)
        {
            sb.AppendLine("## Steps");
            sb.AppendLine();
            sb.AppendLine("| Step | Result | Exit Code |");
            sb.AppendLine("|---|---|---:|");
            foreach (var s in r.Steps)
                sb.AppendLine($"| {Esc(s.Name)} | {(s.Succeeded ? "PASS" : "FAIL")} | {s.ExitCode} |");
            sb.AppendLine();
        }

        if (r.SonarBefore is not null || r.SonarAfter is not null)
        {
            sb.AppendLine("## SonarQube Results");
            sb.AppendLine();

            if (r.SonarBefore is not null)
            {
                sb.AppendLine("### Before");
                AppendSonar(sb, r.SonarBefore);
            }

            if (r.SonarAfter is not null)
            {
                sb.AppendLine("### After");
                AppendSonar(sb, r.SonarAfter);
            }
        }
        else if (r.Sonar is not null)
        {
            sb.AppendLine("## SonarQube Summary");
            sb.AppendLine();
            AppendSonar(sb, r.Sonar);
        }

        if (r.EnforcedRules is not null && r.EnforcedRules.Count > 0)
        {
            sb.AppendLine("## Enforced Rules (PASS or FAIL)");
            sb.AppendLine();
            sb.AppendLine("| Rule | Status |");
            sb.AppendLine("|---|---|");
            foreach (var rr in r.EnforcedRules)
                sb.AppendLine($"| `{Esc(rr.Rule)}` | {rr.Status} |");
            sb.AppendLine();
        }

        if (r.QualityGate is not null)
        {
            sb.AppendLine("## Quality Gate");
            sb.AppendLine();
            sb.AppendLine($"- Passed: **{(r.QualityGate.Passed ? "YES" : "NO")}**");
            sb.AppendLine();
            sb.AppendLine("| Severity | Threshold |");
            sb.AppendLine("|---|---:|");
            foreach (var kv in r.QualityGate.Thresholds)
                sb.AppendLine($"| {kv.Key} | {kv.Value} |");
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine("Generated by QualityAgent.NET");
        return sb.ToString();
    }

    private static void AppendSonar(StringBuilder sb, SonarSummary s)
    {
        if (s.Skipped)
        {
            sb.AppendLine($"SonarQube query was skipped: {Esc(s.SkipReason ?? "unknown reason")}");
            sb.AppendLine();
            return;
        }

        sb.AppendLine($"- BLOCKER: {s.Blocker}");
        sb.AppendLine($"- CRITICAL: {s.Critical}");
        sb.AppendLine($"- MAJOR: {s.Major}");
        sb.AppendLine($"- MINOR: {s.Minor}");
        sb.AppendLine($"- INFO: {s.Info}");
        sb.AppendLine();

        if (s.TopRules.Count > 0)
        {
            sb.AppendLine("#### Top Rules");
            sb.AppendLine();
            sb.AppendLine("| Rule | Count |");
            sb.AppendLine("|---|---:|");
            foreach (var kv in s.TopRules)
                sb.AppendLine($"| `{Esc(kv.Key)}` | {kv.Value} |");
            sb.AppendLine();
        }
    }

    private static string Esc(string s) => s.Replace("|", "\\|");
}
